### ISSUE TITLE
How to ssh to the container&&debug

### ISSUE THREAD

**Issue by SummerSunnyNight** [tonyyxliu/CUHKSZ-CSC4005#19]
I searched across the internet and it seems that ssh to the container is not a recommended operation, and I wonder what is the goal for it?
What's more. it seems that systemctl instruction that is used to start ssh service is banned by docker, are there any way to bypass it?
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/73238595/a164866e-c3a3-4a78-bf19-aa14abd36a21)
and for the debugging, the recommended way is still printf right? Are there any way like breakpoint? Thanks.

**Comment by tonyyxliu** [comment]
SSH is just one way to write programs in your docker container, and it is not necessary. Apart from SSH, you can also mount shard folders to your docker container so that you can write programs on your host system and compile & execute in the container. You can even manually copy the files to the container. All these ways are OK, choose the one you like.

As for debugging, it is usually integrated with the IDE. If you use CLion, then you can debug your program with breakpoint or valgrind.
