### ISSUE TITLE
Question about sequential B part code performance

### ISSUE THREAD

**Issue by maxreo** [tonyyxliu/CUHKSZ-CSC4005#26]
I ran the sequential_PartB code provided on github, why it is much slower than the baseline performance?

![微信图片_20230927151657](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/88414962/9c1a860c-19c2-48ed-a6c8-8ec874640203)

![微信图片_20230927151820](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/88414962/f006fad4-e59d-4ef8-a2cc-c91985b77dc0)

**Comment by szjiozi** [comment]
I have the same problems! My performance is close to yours

**Comment by tonyyxliu** [comment]
The sequential implementation we gave to you is a very naive version, and it can be optimized to reach the baseline performance with the techniques given as the hints in the Project 1 instruction. I remember that I have said it somewhere, but it turns out that it is not included in the instruction. I will update it ASAP. Thanks for pointing out!

**Comment by tonyyxliu** [comment]
Just try to avoid nested for loop, which often leads to bad parallelism. For example, we assume that the filter size is always 3, and why do we need two for loops (for -1 to 1) to handle the computation? Can we do it directly as 9 lines of codes so that the memory access is more efficient?

**Comment by maxreo** [comment]
> Just try to avoid nested for loop, which often leads to bad parallelism. For example, we assume that the filter size is always 3, and why do we need two for loops (for -1 to 1) to handle the computation? Can we do it directly as 9 lines of codes so that the memory access is more efficient?

I see. Thank you!
