### ISSUE TITLE
command order in makefile affects compilation for CUDA

### ISSUE THREAD

**Issue by kimhw99** [tonyyxliu/CUHKSZ-CSC4005#31]
![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/105446294/3732d46a-f06d-44d4-b2c7-6687e5fb570e)

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/105446294/91ca2fc9-dc02-4053-a8a0-767764540759)
When the makefile order is CUDA A - CUDA B - OpenACC A, the compilation is successful.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/105446294/5b17bfc8-88a6-481c-b470-69d2544d2fd3)

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/105446294/14b13cd8-94f5-4229-8568-faa33df3a5eb)
When the order is CUDA A - OpenACC A - CUDA B, the compilation fails

for both cases, i made cuda_PartB.cu's code the same as cuda_PartA.cu (greyscale implementation).

**Comment by zihan0822** [comment]
That was probably because the compiler option you set for c++ in $CMAKE_CXX_FLAGS, here is `-acc` will be propagated to cuda compiler nvcc. But it does not support this option. So the last compile sequence you show does not work.
If you really want to do it in order of `cuda A - openacc - cuda B`. You can either remove `-acc` option before compile `cuda B` or set the c++ compile flag temporarily by, instead of altering $CMAKE_CXX_FLAGS , doing `target_compile_options(openacc_PartB PRIVATE acc)`. In this way, the option you set for c++ compiler will not tamper with nvcc. This propagation behavior probably comes from a global setting in the cmake config file for cuda. The rationale for this setting is that most of the cpp options can be used by nvcc as well. But here it's an exception.
I know this, because I encountered this a while ago, imao.
