### ISSUE TITLE
What should we include when we submit the assignment?

### ISSUE THREAD

**Issue by RuiRuihigh** [tonyyxliu/CUHKSZ-CSC4005#39]
I do not fully understand the meaning of the source code that we need to submit. Does it include CMakeList.txt, .sh file, utils.cpp, and so on? Or only those six cpp files about Part B? Wish you could clearly declare them.

**Comment by tonyyxliu** [comment]
Hi @RuiRuihigh 

I have made an announcement before about your question. Of course it should include the utils.cpp/hpp and CMakeLists.txt files, otherwise, your programs cannot be compiled correctly. One thing to note is that all the images should not be included to avoid large-size submission.

### What to Submit on BB?

You should submit a zip file containing the source codes of your project (all the images should not be included in your submission for much smaller size), and one report in PDF format. Both of these two should be named as your student ID, for example:

118010200.zip (Source Codes)

118010200.pdf (Report)
