### ISSUE TITLE
g++: error: unrecognized command line option ‘-mavx512f’

### ISSUE THREAD

**Issue by Lee-7102** [tonyyxliu/CUHKSZ-CSC4005#4]
When I compile avx512_vectorized_addition.cpp, it said "g++: error: unrecognized command line option ‘-mavx512f’".
<img width="619" alt="issue1" src="https://github.com/tonyyxliu/CSC4005-2023Fall/assets/78122108/661c3650-69bb-4507-a733-dff933a5a19f">

**Comment by tonyyxliu** [comment]
It seems strange to me since avx512f is supported by the cluster CPU. Could you please tell me your student ID so that I can login your account and help you fix it? If you have changed the password, please send a email to me about your student ID and password.

![image](https://github.com/tonyyxliu/CSC4005-2023Fall/assets/62693471/0be57f03-4398-424c-a42a-4c4de526679f)

**Comment by Lee-7102** [comment]
My student ID is 120090702.

    Sincerely,
Li, Yiqian

发件人: Yuxuan ***@***.***>
发送时间: 2023年9月11日 11:17
收件人: ***@***.***>
抄送: Yiqian Li (SDS, ***@***.***>; State ***@***.***>
主题: Re: [tonyyxliu/CSC4005-2023Fall] g++: error: unrecognized command line option ‘-mavx512f’ (Issue #4)


It seems strange to me since avx512f is supported by the cluster CPU. Could you please tell me your student ID so that I can login your account and help you fix it? If you have changed the password, please send a email to me about your student ID and password.

[image]<https://user-images.githubusercontent.com/62693471/266897955-0be57f03-4398-424c-a42a-4c4de526679f.png>

―

**Comment by tonyyxliu** [comment]
Hi Yiqian @Lee-7102 

I just login your account but found that everything worked as expected. I have attached the terminal input & output below. I don't know why this failed in your computer. Maybe you should bring your laptop to the classroom on the tutorials this week.

```bash
[120090702@node21 sample_programs]$ pwd
/nfsmnt/120090702/sample_programs   
[120090702@node21 sample_programs]$ ls
avx512_vectorized_addition      cuda_hello.cu  mpi_hello.cpp     openacc_parallel.cpp  openmp_hello.cpp  pthread_hello.cpp
avx512_vectorized_addition.cpp  mpi_hello      openacc_parallel  openmp_hello          pthread_hello     README.md        
[120090702@node21 sample_programs]$ g++ -mavx512f avx512_vectorized_addition.cpp -o avx512_vectorized_addition
[120090702@node21 sample_programs]$ ./avx512_vectorized_addition
c[0] = 0  
c[1] = 3  
c[2] = 6  
c[3] = 9  
c[4] = 12 
c[5] = 15 
c[6] = 18 
c[7] = 21 
c[8] = 24 
c[9] = 27 
c[10] = 30
c[11] = 33
c[12] = 36
c[13] = 39
c[14] = 42
c[15] = 45
```

**Comment by Lee-7102** [comment]
OK. Thank you, TA!

    Sincerely,
Li, Yiqian

发件人: Yuxuan ***@***.***>
发送时间: 2023年9月11日 12:18
收件人: ***@***.***>
抄送: Yiqian Li (SDS, ***@***.***>; ***@***.***>
主题: Re: [tonyyxliu/CSC4005-2023Fall] g++: error: unrecognized command line option ‘-mavx512f’ (Issue #4)


Hi Yiqian @Lee-7102<https://github.com/Lee-7102>

I just login your account but found that everything worked as expected. I have attached the terminal input & output below. I don't know why this failed in your computer. Maybe you should bring your laptop to the classroom on the tutorials this week.

***@***.*** sample_programs]$ pwd

/nfsmnt/120090702/sample_programs

***@***.*** sample_programs]$ ls

avx512_vectorized_addition      cuda_hello.cu  mpi_hello.cpp     openacc_parallel.cpp  openmp_hello.cpp  pthread_hello.cpp

avx512_vectorized_addition.cpp  mpi_hello      openacc_parallel  openmp_hello          pthread_hello     README.md

***@***.*** sample_programs]$ g++ -mavx512f avx512_vectorized_addition.cpp -o avx512_vectorized_addition

***@***.*** sample_programs]$ ./avx512_vectorized_addition

c[0] = 0

c[1] = 3

c[2] = 6

c[3] = 9

c[4] = 12

c[5] = 15

c[6] = 18

c[7] = 21

c[8] = 24

c[9] = 27

c[10] = 30

c[11] = 33

c[12] = 36

c[13] = 39

c[14] = 42

c[15] = 45

―

**Comment by Eightina** [comment]
I encountered this problem as well, while another classmate i know did not. I wondered if it was due to different gcc versions, so I checked it and there was indeed a significant different in our gcc version number, with the gcc on my node
being 4.8.5, and the gcc on my classmate's node being 7.3.1.

However, it seems I cannot update my gcc by myself. So I'm also looking forward to any possible solutions.

**Comment by I-am-Future** [comment]
Hi all, 
I met the same problem on my own desktop's docker image. My processor is 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz, and result from `/proc/cpuinfo` indicates that my processor supports avx512f instruction set. In addition, `g++ --version` says version is `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`. From [here](https://stackoverflow.com/questions/57043592/compilation-error-for-avx512-is-it-a-gcc-issue), I guess that's because g++ 4.8 in that docker image does not support avx512f?

**Comment by tonyyxliu** [comment]
Yes, if you find your gcc version is 4.8.5 on the cluster, please refer to this [updated issue 3](https://github.com/tonyyxliu/CSC4005-2023Fall/issues/3) and add gcc-7 bin to the system $PATH.

**Comment by 58191554** [comment]
> Hi all, I met the same problem on my own desktop's docker image. My processor is 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz, and result from `/proc/cpuinfo` indicates that my processor supports avx512f instruction set. In addition, `g++ --version` says version is `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`. From [here](https://stackoverflow.com/questions/57043592/compilation-error-for-avx512-is-it-a-gcc-issue), I guess that's because g++ 4.8 in that docker image does not support avx512f?

u can upgrade it in docker 😅

**Comment by I-am-Future** [comment]
> > Hi all, I met the same problem on my own desktop's docker image. My processor is 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz, and result from `/proc/cpuinfo` indicates that my processor supports avx512f instruction set. In addition, `g++ --version` says version is `g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`. From [here](https://stackoverflow.com/questions/57043592/compilation-error-for-avx512-is-it-a-gcc-issue), I guess that's because g++ 4.8 in that docker image does not support avx512f?
> 
> u can upgrade it in docker 😅

Yeah, of course, thank you for your solution. I have already done this last week.

**Comment by 58191554** [comment]
乐
________________________________
发件人: Lai Wei ***@***.***>
发送时间: 2023年9月19日 19:51
收件人: tonyyxliu/CSC4005-2023Fall ***@***.***>
抄送: Zhen Tong (SDS, 120090694) ***@***.***>; Comment ***@***.***>
主题: Re: [tonyyxliu/CSC4005-2023Fall] g++: error: unrecognized command line option ‘-mavx512f’ (Issue #4)


Hi all, I met the same problem on my own desktop's docker image. My processor is 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz, and result from /proc/cpuinfo indicates that my processor supports avx512f instruction set. In addition, g++ --version says version is g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44). From here<https://stackoverflow.com/questions/57043592/compilation-error-for-avx512-is-it-a-gcc-issue>, I guess that's because g++ 4.8 in that docker image does not support avx512f?

u can upgrade it in docker 😅

Yeah, of course, thank you for your solution. I have already done this last week. Can't figure out what your emoji means.
