### ISSUE TITLE
The path to executable files is not correct in sbatch_PartA.sh

### ISSUE THREAD

**Issue by LouisCroix** [tonyyxliu/CUHKSZ-CSC4005#68]
The path to executable files generated by cmake in sbatch_PartA.sh is ${CURRENT_DIR}/../../build/src/cpu/file_name, which seems to lack the CMakeFiles folder between the cpu folder and file_name.

**Comment by EnderturtleOrz** [comment]
Can you show me the photo of your folder structure after building? It seems to work well for me.

**Comment by LouisCroix** [comment]
![1726762457420](https://github.com/user-attachments/assets/1d78f715-4c3f-4e97-a30f-06ec2b6d2de0)
![1726762494280](https://github.com/user-attachments/assets/b8fd5b4f-bb98-4d80-9e48-ad99143a8170)
Yes. Here are the screenshots of my folder structure and the path in sbatch_PartA.sh. Thanks for your reply.

**Comment by EnderturtleOrz** [comment]
Sorry, I don't find your executable files are under `build/src/cpu/CMakeFiles`, like `mpi_PartA`.  In fact, `CMakeFiles` will not contain any executable files. They should under `build/src/cpu`. You can use command `ls` to check files under this path.
Or you just show me files under `build/src/cpu` completely instead of `build/src/cpu/CMakeFiles` and I can provide more help.

**Comment by LouisCroix** [comment]
Oops, this issue seems to be caused by my fault for not following the instructions in Readme in project1. Sorry to trouble you with this.
